language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
   - sudo apt-get update -qq
   - sudo apt-get -y install libavahi-cil-dev libavahi-client-dev libavahi-common-dev libavahi-compat-libdnssd-dev libavahi-core-dev libavahi-glib-dev libavahi-gobject-dev libcups2-dev libcupscgi1-dev libcupsfilters-dev libcupsimage2-dev libcupsmime1-dev libcupsppdc1-dev libfontembed-dev libpoppler-cpp-dev libijs-dev libpng12-dev zlib1g-dev libtiff5-dev libopenjpeg-dev libfreetype6-dev libfontconfig1-dev

script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - wget -c -q "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file ./APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./cups-filters*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

####### wir brauchen noch ein .desktop file

#    Poppler, libijs, freetype, fontconfig, and liblcms (liblcms2 recommended) 
#    must be installed to be able to compile this package.
#
#    Note that Poppler has to be compiled with the
#    "--enable-poppler-cpp" configure option (or the
#    "libpoppler-cpp-dev(el)" package has to be installed if the
#    Poppler packages from a Linux distribution are used).
#
#    Besides these tools you'll want the JPEG, PNG, TIFF, ZLIB libraries for
#    image support. CUPS Filters will compile and run without these, however
#    you'll miss out on many of the features provided by CUPS Filters.
#
#    To get cups-browsed, the daemon to browse Bonjour broadcasts of
#    remote CUPS queues and make the queues available locally, you also
#    need libavahi-common and libavahi-client.
